name: Artifact Demo
on:
  push:
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate report
        run: |
          mkdir -p reports
          echo "Run $GITHUB_RUN_NUMBER on $GITHUB_REF" > reports/summary.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: run-report
          path: reports/
          retention-days: 7

