name: Run Only When Files Change
on:
  pull_request:
permissions:
  contents: read
jobs:
  selective:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: changed
        uses: tj-actions/changed-files@v45
      - name: List changed Markdown files
        if: steps.changed.outputs.any_changed == 'true'
        run: |
          echo "All changed: ${{ steps.changed.outputs.all_changed_files }}"
          echo "Changed .md:  ${{ steps.changed.outputs.all_modified_files }}"

