name: Scheduled Maintenance
on:
  schedule:
    - cron: '0 9 * * 1'   # Mondays 09:00 UTC
  workflow_dispatch:
permissions:
  contents: read
jobs:
  housekeeping:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Weekly job ran at ${{ github.run_started_at }}"

